# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Emma
tagline:          'tagline'
description:      'description'
url:              http://www.emame.se

author:
  name:           'Emma Melander'
  twitter:        https://twitter.com/emwie_
  linkedin:       https://se.linkedin.com/in/emmamelander
  github:         https://github.com/emame/emma

paginate:         5
gems: [jekyll-paginate]

